### ISSUE TITLE
Default value for config arguments

### ISSUE THREAD

**Issue by dogoku** [chevex/yargs#12]
Given the following setup

    yargs.config("c").describe("c", "Config file path").default("c","config.json")

It seems that even though the default value gets read (eventually), the config file is never read, since `setArg` is not called for a default value.

**Comment by soluml** [comment]
Still experiencing this issue as well!

**Comment by mathroc** [comment]
@bcoe is anything preventing you to do a PR based on your "12-fix" branch ? I've been using it and it's working great :+1:

**Comment by bcoe** [comment]
@mathroc, @dogoku mind giving this branch a try:

https://github.com/chevex/yargs/pull/79

If it solves your problems I'd like to merge it and release version 2.0 of yargs.

**Comment by dogoku** [comment]
I'll give it a go later today

**Comment by mathroc** [comment]
@bcoe I tried to install `bcoe/yargs#test-fix-config-changes` but it seems the branch is not present anymore in your repository. am I missing something ?

**Comment by bcoe** [comment]
@mathroc sorry for the confusion, I'm actually committing directly to the `yargs` repo now, and have a branch  called `bcoe/test-fix-config-changes`.

FYI, I just bounced the behavior we've been bike-shedding off my coworker @zeke at npm, he agrees with CLI arguments smashing config arguments.

**Comment by zeke** [comment]
smash

**Comment by mathroc** [comment]
@bcoe oh I didn't notice, it's better but there is still some case not working I think, I'll explain it on the PR

**Comment by bcoe** [comment]
This problem should now be fixed on master, via:

https://github.com/chevex/yargs/pull/79

**Comment by mathroc** [comment]
it's working great! thank you!
