### ISSUE TITLE
Can we also have a epilog that can be printed after "Options"?

### ISSUE THREAD

**Issue by w9** [chevex/yargs#14]
Sometimes I need to mention a little more information for the users, such as:

```
Usage: ...

Options: ...

Documentation can be found at http://nodejs.org/
```

it would be nice to encapsulate this into the `yargs` object.

**Comment by bcoe** [comment]
@w9 @nylen in the case of a failure, do you think the epilogue should be displayed above or below the error message, should it be displayed?

**Comment by w9** [comment]
@bcoe I don't think any help message should be displayed in the case of a failure. It should only show when the user asks for it. Isn't it?

**Comment by nylen** [comment]
That's what the GNU utilities do, at least:

```
james@computron ~ $ cat --error
cat: unrecognized option '--error'
Try 'cat --help' for more information.

[1]james@computron ~ $ grep --error
grep: unrecognized option '--error'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

[2]james@computron ~ $ ls --error
ls: unrecognized option '--error'
Try 'ls --help' for more information.
```

**Comment by bcoe** [comment]
There's a flag showHelpOnFail, in the case that this is true, errors after
epilogue?

**Comment by nylen** [comment]
I agree with using `showHelpOnFail` for that purpose.

I have usually shown the error message, then the help, as if to say "here's what went wrong" ... "here's how you fix it".  The drawback of that is when you have really long option lists it's not as clear what's going on.  So no strong preference here as far as order :)

**Comment by w9** [comment]
@bcoe @nylen I think we should distinguish the epilogue of the help message, and the epilogue of a failure. Because sometimes I see people add copyright or contact or even promotional information at the end of their help message. The purpose of a epilogue in the help message may differ drastically with a "possible solution" prompt that needs to appear at the end of an error.

**Comment by bcoe** [comment]
@w9 I've added the `epilog` and `epilogue` option in yargs 3.0, for printing messages when an error occurs see:

(showHelpOnFail)[https://github.com/chevex/yargs#showhelponfailenable-message]
