### ISSUE TITLE
Strict type usage

### ISSUE THREAD

**Issue by 3y3** [chevex/yargs#17]
With config:
```js
{
'web-port': {
    alias: ['p', 'port'],
    type: 'number'
  },
  nodejs: {
    type: 'string'
  }
}
```
next command line
```node-debug --web-port 5858 --nodejs --max-stack-trace=90 --nodejs --harmony app.js --opt 1``` 
will parsed as
```js
{
  'web-port': 5858,
  'nodejs': true,
  '--max-stack-trace': 90,
  'harmony': true,
  ...
}
```
What about check opt type and if it's not boolean get next ard as value?
Expected result:
```js
{
  'web-port': 5858,
  'nodejs': [ '--max-stack-trace=90','--harmony'],
  ...
}
```

**Comment by bcoe** [comment]
@3y3 this would make it difficult to specify an empty string, as of:

https://github.com/chevex/yargs/commit/9ae61dd005fd72571469fd327877853e0fbc44ce

You could now run:

```bash
node-debug --web-port 5858 --nodejs --max-stack-trace=90 --nodejs --harmony app.js --opt 1
```

And it result in:

```js
{
  nodejs: ['', '']
}
```

I think a way to get the functionality you're looking for, which would be less ambiguous, would be:

```bash
node-debug --web-port 5858 --nodejs '--max-stack-trace=90' --nodejs '--harmony app.js' --opt 1
```
