### ISSUE TITLE
Strange behavior with --sort option

### ISSUE THREAD

**Issue by nylen** [chevex/yargs#51]
If `sort` is specified as an option name, then a type hint will be printed (this never seems to happen otherwise) and a default value will somehow be pulled from `toString()` on the native `sort` function.  This doesn't happen if another name is specified first, then `sort` is specified as an alias.  Example:

---

File `test-sort-first.js`:
```js
var program = require('yargs')
    .option('sort', {
        alias    : 's',
        describe : 'sort order'
    });

program.showHelp();
```
Output:
```
Options:
  --sort, -s  sort order  [string]  [default: function sort() { [native code] }]
```

---

File `test-sort-second.js`:
```js
var program = require('yargs')
    .option('s', {
        alias    : 'sort',
        describe : 'sort order'
    });

program.showHelp();
```
Output:
```
Options:
  -s, --sort  sort order
```

**Comment by bcoe** [comment]
@nylen this problem should now fixed on main, via:

https://github.com/chevex/yargs/pull/74

**Comment by nylen** [comment]
![Fix all the things!](http://www.quickmeme.com/img/04/04bb8d2a6813ab490ffaa7e01ba937ec2f99c66a799fabf5c1ebbb237a5090e9.jpg)

Excellent, thanks for the fix!
