### ISSUE TITLE
Non-hyphenated options interpreted as numbers without double dash

### ISSUE THREAD

**Issue by frontierpsycho** [chevex/yargs#56]
I want to pass a list of IDs as CL arguments to a script, and interpret them as strings (to preserve possible leading zeros). When I pass non-hyphenated options, they get interpreted as strings only if I put them after a double dash (--). Otherwise, they get interpreted as numbers.

Is this intended behaviour? Shouldn't yargs interpret NHOs the same, with or without a double dash? Would it be possible to have an extra method that tells yargs how to interpret NHOs?

I am aware that I can just use a named option many times, and that produces a list, but it seems extraneous to repeat the option name all the time.

**Comment by frontierpsycho** [comment]
I still see it. Try running this simple node app:

```
console.log(require('yargs').argv._)
```

And run it like this:

```
$ node test.coffee 0123 0234
```

and then like this:

```
$ node test.coffee -- 0123 0234
```

The output is first `[ 123, 234 ]` and then `[ '0123', '0234' ]`.

**Comment by bcoe** [comment]
@frontierpsycho you can use `string('_')` to prevent non-hyphenated arguments from being interpreted as numbers, I've documented this here:

https://github.com/chevex/yargs/pull/84/files
