### ISSUE TITLE
How to document non switch arguments

### ISSUE THREAD

**Issue by sukima** [chevex/yargs#62]
How can I (or can I) add a describe for items I use via the `argv._` variable?

```javascript
var argv = require('yargs')
  .usage('Usage: $0 [FILE]')
  .describe('FILE', 'The file to use')
  .help('help')
  .alias('help', 'h')
  .argv;
```

#### output:

```
node ./bin/yargs_example.js [FILE]


Options:
  --FILE        The file to use
  --help, -h    Show help
```

**Comment by stramel** [comment]
:+1: I would also like to know this for usage with Gulp

**Comment by bcoe** [comment]
@sukima what do you think the ideal would be for documenting `_`, do any other CLI apps come to mind as a point of reference?

**Comment by sukima** [comment]
Well I took about 5 minutes to check the help message of some various Unix tools. Seems documentation on the `_` type of arguments is not very common. I did find something similar to what I was looking for with the `diff` command (Mac OS X Yosemite):

    $ diff --help
    Usage: diff [OPTION]... FILES
    Compare files line by line.

    [... snipped long list of args ...]

    FILES are `FILE1 FILE2' or `DIR1 DIR2' or `DIR FILE...' or `FILE... DIR'.
    If --from-file or --to-file is given, there are no restrictions on FILES.
    If a FILE is `-', read standard input.

    Report bugs to <bug-gnu-utils@gnu.org>.

Maybe something like that?

**Comment by bcoe** [comment]
@sukima, @stramel in yargs@3.x, I've introduced the concept of `command`.

Command allows you to describe each of the `_` options available in your application:

https://github.com/chevex/yargs#commandcmd-desc

```js
var argv = require('yargs')
  .command('start', 'start the application');
  .command('stop', 'stop the application');
```

Does this do the trick for you?

**Comment by stramel** [comment]
@bcoe That looks like it will do the trick, thanks!
