### ISSUE TITLE
Allow undefined in boolean field parsing

### ISSUE THREAD

**Issue by ashi009** [chevex/yargs#69]
I want to get the user's preference on update or not, so I added a `--update` flag to parsing options:
```
var argv = yargs.Options('--update', {
  boolean: true
}).argv;
```

In this case, when user set `--update` in the arguments, `argv.update` will be set, and when user miss this flag, `false` will be put there.  But a more sensible interpretation is that user didn't give a specific preference, neither did my parsing option, in which case `undefined` seems more favorable. And, in this context, whether to update should be determined by some mechanism like last update time.

I propose that, allow return `undefined` when `default: undefined` is specifically set.

**Comment by bcoe** [comment]
addressed in:

https://github.com/chevex/yargs/pull/87
