### ISSUE TITLE
Calling help throws error

### ISSUE THREAD

**Issue by kevinsawicki** [chevex/yargs#71]
Here is a reduced example that was expected to print out `foo`

```js
require('yargs')([]).usage('foo').help()
```

But instead:

```
TypeError: Cannot read property 'newAliases' of undefined
    at Object.Argv.self.help (/Users/kevin/app/node_modules/yargs/index.js:355:44)
```

Version 1.3.3

**Comment by bcoe** [comment]
@kevinsawicki this issued should be addressed in:

https://github.com/chevex/yargs/pull/72
