### ISSUE TITLE
What does the 'array of options' do in .check(fn)?

### ISSUE THREAD

**Issue by giacecco** [chevex/yargs#76]
It's not clear what you describe at https://github.com/chevex/yargs#checkfn . What does the second parameter of *fn* do? Can you offer an example?

I would also suggest that the check fails if *fn* returns *anything but true*, rather than *false*. The rationale is that most people will use *check* to check that the user specified conditional arguments, e.g. *argument2* is needed only if *argument1* is specified. You would instinctively write that like this:

    var require('yargs')
        .check(function (argv) {
            return !argv.argument1 || (argv.argument1 && argv.argument2);
        })
        .argv;

That code would **not** catch the user specifying *argument1* but forgetting about *argument2*, though, because true && undefined is undefined, not false! To make that work, I need to change it to:

    var require('yargs')
        .check(function (argv) {
            return !argv.argument1 || (argv.argument1 && argv.argument2) || false;
        })
        .argv;

What do you reckon?

**Comment by bcoe** [comment]
@giacecco I like the idea of having any non-truthy return result in the check failing., would you like to take a crack at the pull-request?

I'm also slightly stumped by the value of the second `aliases` argument, perhaps @chevex can shed some light on this?

**Comment by bcoe** [comment]
@giacecco in yargs 3.0, check will now fail if any non-truthy value is returned:

https://github.com/chevex/yargs/releases/tag/3.0.2

with regards to the second parameter passed to check, take a look at `validation.js`, there are a few validation rules that use the `aliases` lookup; I think the idea was that you'd be able to write an equivalent  validation with `check`.
