### ISSUE TITLE
yargs.rebase function is worthless?!

### ISSUE THREAD

**Issue by ivan-kleshnin** [chevex/yargs#77]
As native `path.relative` has the same effect.

```
console.log(path.relative("/this/is/base", "/this/is/base/file"));  // -> file
console.log(yargs.rebase("/this/is/base", "/this/is/base/file"));   // -> ./file

console.log(path.relative("/this/is/base/file", "/this/is/base/")); // -> ..
console.log(yargs.rebase("/this/is/base/file", "/this/is/base"));   // -> ..
```

If only the difference between `file` and `./file` is not critical...
And even than you can build `yargs.rebase` on top of `path.relative` with great simplification. 
Moreover, currently `.rebase` is trailing-slash-sensitive which is generally bad at FS operations.

**Comment by bcoe** [comment]
@ivan-kleshnin I've switched to using path.relative() in:

https://github.com/chevex/yargs/pull/82

See any problems?

**Comment by ivan-kleshnin** [comment]
No, thanks!
