### ISSUE TITLE
End --version output with newline

### ISSUE THREAD

**Issue by nylen** [chevex/yargs#81]
Per recent discussion in #49.

Current behavior:

```
james@computron ~ $ yargs --version
1.0.1james@computron ~ $
```

Desired behavior:

```
james@computron ~ $ yargs --version
1.0.1
james@computron ~ $
```

See also #58 and ping @eush77

**Comment by eush77** [comment]
I would like to see a54d068 being reverted.

I don't think the use of `process.stdout.write` here is justified enough (even when `tty.isatty(1) == false`) since the rest of the code uses `console.log` and `console.error` for printing stuff.

**Comment by bcoe** [comment]
Along with tons of bug-fixes to terminal/wrapping, yargs@3.x again adds a newline after version:

https://github.com/chevex/yargs/releases/tag/3.0.2
